"""TDX City resolver for common Chinese aliases."""

from __future__ import annotations

CITY_ALIASES = {
    # 直轄市
    "台北": {"city": "Taipei", "label": "臺北市"},
    "臺北": {"city": "Taipei", "label": "臺北市"},
    "台北市": {"city": "Taipei", "label": "臺北市"},
    "臺北市": {"city": "Taipei", "label": "臺北市"},
    "新北": {"city": "NewTaipei", "label": "新北市"},
    "新北市": {"city": "NewTaipei", "label": "新北市"},
    "桃園": {"city": "Taoyuan", "label": "桃園市"},
    "桃園市": {"city": "Taoyuan", "label": "桃園市"},
    "台中": {"city": "Taichung", "label": "臺中市"},
    "臺中": {"city": "Taichung", "label": "臺中市"},
    "台中市": {"city": "Taichung", "label": "臺中市"},
    "臺中市": {"city": "Taichung", "label": "臺中市"},
    "台南": {"city": "Tainan", "label": "臺南市"},
    "臺南": {"city": "Tainan", "label": "臺南市"},
    "台南市": {"city": "Tainan", "label": "臺南市"},
    "臺南市": {"city": "Tainan", "label": "臺南市"},
    "高雄": {"city": "Kaohsiung", "label": "高雄市"},
    "高雄市": {"city": "Kaohsiung", "label": "高雄市"},
    # 省轄市
    "基隆": {"city": "Keelung", "label": "基隆市"},
    "基隆市": {"city": "Keelung", "label": "基隆市"},
    "新竹市": {"city": "Hsinchu", "label": "新竹市"},
    "嘉義市": {"city": "ChiayiCity", "label": "嘉義市"},
    # 縣
    "新竹": {"city": "HsinchuCounty", "label": "新竹縣"},
    "新竹縣": {"city": "HsinchuCounty", "label": "新竹縣"},
    "苗栗": {"city": "MiaoliCounty", "label": "苗栗縣"},
    "苗栗縣": {"city": "MiaoliCounty", "label": "苗栗縣"},
    "彰化": {"city": "ChanghuaCounty", "label": "彰化縣"},
    "彰化縣": {"city": "ChanghuaCounty", "label": "彰化縣"},
    "南投": {"city": "NantouCounty", "label": "南投縣"},
    "南投縣": {"city": "NantouCounty", "label": "南投縣"},
    "雲林": {"city": "YunlinCounty", "label": "雲林縣"},
    "雲林縣": {"city": "YunlinCounty", "label": "雲林縣"},
    "嘉義": {"city": "ChiayiCounty", "label": "嘉義縣"},
    "嘉義縣": {"city": "ChiayiCounty", "label": "嘉義縣"},
    "屏東": {"city": "PingtungCounty", "label": "屏東縣"},
    "屏東縣": {"city": "PingtungCounty", "label": "屏東縣"},
    "宜蘭": {"city": "YilanCounty", "label": "宜蘭縣"},
    "宜蘭縣": {"city": "YilanCounty", "label": "宜蘭縣"},
    "花蓮": {"city": "HualienCounty", "label": "花蓮縣"},
    "花蓮縣": {"city": "HualienCounty", "label": "花蓮縣"},
    "台東": {"city": "TaitungCounty", "label": "臺東縣"},
    "臺東": {"city": "TaitungCounty", "label": "臺東縣"},
    "台東縣": {"city": "TaitungCounty", "label": "臺東縣"},
    "臺東縣": {"city": "TaitungCounty", "label": "臺東縣"},
    "澎湖": {"city": "PenghuCounty", "label": "澎湖縣"},
    "澎湖縣": {"city": "PenghuCounty", "label": "澎湖縣"},
    "金門": {"city": "KinmenCounty", "label": "金門縣"},
    "金門縣": {"city": "KinmenCounty", "label": "金門縣"},
    "連江": {"city": "LienchiangCounty", "label": "連江縣"},
    "連江縣": {"city": "LienchiangCounty", "label": "連江縣"},
    "馬祖": {"city": "LienchiangCounty", "label": "連江縣"},
}

# city code → 中文標籤（district fallback 回傳用）
_CITY_CODE_TO_LABEL: dict[str, str] = {
    "Taipei": "臺北市",
    "NewTaipei": "新北市",
    "Taoyuan": "桃園市",
    "Taichung": "臺中市",
    "Tainan": "臺南市",
    "Kaohsiung": "高雄市",
    "Keelung": "基隆市",
    "Hsinchu": "新竹市",
    "ChiayiCity": "嘉義市",
    "HsinchuCounty": "新竹縣",
    "MiaoliCounty": "苗栗縣",
    "ChanghuaCounty": "彰化縣",
    "NantouCounty": "南投縣",
    "YunlinCounty": "雲林縣",
    "ChiayiCounty": "嘉義縣",
    "PingtungCounty": "屏東縣",
    "YilanCounty": "宜蘭縣",
    "HualienCounty": "花蓮縣",
    "TaitungCounty": "臺東縣",
    "PenghuCounty": "澎湖縣",
    "KinmenCounty": "金門縣",
    "LienchiangCounty": "連江縣",
}

# 鄉鎮市區 → 縣市 TDX code（Wikipedia 資料，僅收無歧義項目）
# 跨縣市同名者（大安區/東區/南區/北區/西區/中正區/信義區/中山區）收在 AMBIGUOUS_DISTRICTS
DISTRICT_TO_CITY: dict[str, str] = {
    # ── 新北市 ──────────────────────────────────────────────
    "萬里區": "NewTaipei",
    "金山區": "NewTaipei",
    "板橋區": "NewTaipei",
    "汐止區": "NewTaipei",
    "深坑區": "NewTaipei",
    "石碇區": "NewTaipei",
    "瑞芳區": "NewTaipei",
    "平溪區": "NewTaipei",
    "雙溪區": "NewTaipei",
    "貢寮區": "NewTaipei",
    "新店區": "NewTaipei",
    "坪林區": "NewTaipei",
    "烏來區": "NewTaipei",
    "永和區": "NewTaipei",
    "中和區": "NewTaipei",
    "土城區": "NewTaipei",
    "三峽區": "NewTaipei",
    "樹林區": "NewTaipei",
    "鶯歌區": "NewTaipei",
    "三重區": "NewTaipei",
    "新莊區": "NewTaipei",
    "泰山區": "NewTaipei",
    "林口區": "NewTaipei",
    "蘆洲區": "NewTaipei",
    "五股區": "NewTaipei",
    "八里區": "NewTaipei",
    "淡水區": "NewTaipei",
    "三芝區": "NewTaipei",
    "石門區": "NewTaipei",
    # ── 臺北市（跳過歧義：中正區/中山區/大安區/信義區）──────────
    "大同區": "Taipei",
    "松山區": "Taipei",
    "萬華區": "Taipei",
    "士林區": "Taipei",
    "北投區": "Taipei",
    "內湖區": "Taipei",
    "南港區": "Taipei",
    "文山區": "Taipei",
    # ── 桃園市 ──────────────────────────────────────────────
    "中壢區": "Taoyuan",
    "平鎮區": "Taoyuan",
    "龍潭區": "Taoyuan",
    "楊梅區": "Taoyuan",
    "新屋區": "Taoyuan",
    "觀音區": "Taoyuan",
    "桃園區": "Taoyuan",
    "龜山區": "Taoyuan",
    "八德區": "Taoyuan",
    "大溪區": "Taoyuan",
    "復興區": "Taoyuan",
    "大園區": "Taoyuan",
    "蘆竹區": "Taoyuan",
    # ── 臺中市（跳過歧義：東區/南區/西區/北區/大安區）────────────
    "中區": "Taichung",
    "北屯區": "Taichung",
    "西屯區": "Taichung",
    "南屯區": "Taichung",
    "太平區": "Taichung",
    "大里區": "Taichung",
    "霧峰區": "Taichung",
    "烏日區": "Taichung",
    "豐原區": "Taichung",
    "后里區": "Taichung",
    "石岡區": "Taichung",
    "東勢區": "Taichung",
    "和平區": "Taichung",
    "新社區": "Taichung",
    "潭子區": "Taichung",
    "大雅區": "Taichung",
    "神岡區": "Taichung",
    "大肚區": "Taichung",
    "沙鹿區": "Taichung",
    "龍井區": "Taichung",
    "梧棲區": "Taichung",
    "清水區": "Taichung",
    "大甲區": "Taichung",
    "外埔區": "Taichung",
    # ── 臺南市（跳過歧義：東區/南區/北區）─────────────────────
    "中西區": "Tainan",
    "安平區": "Tainan",
    "安南區": "Tainan",
    "永康區": "Tainan",
    "歸仁區": "Tainan",
    "新化區": "Tainan",
    "左鎮區": "Tainan",
    "玉井區": "Tainan",
    "楠西區": "Tainan",
    "南化區": "Tainan",
    "仁德區": "Tainan",
    "關廟區": "Tainan",
    "龍崎區": "Tainan",
    "官田區": "Tainan",
    "麻豆區": "Tainan",
    "佳里區": "Tainan",
    "西港區": "Tainan",
    "七股區": "Tainan",
    "將軍區": "Tainan",
    "學甲區": "Tainan",
    "北門區": "Tainan",
    "新營區": "Tainan",
    "後壁區": "Tainan",
    "白河區": "Tainan",
    "東山區": "Tainan",
    "六甲區": "Tainan",
    "下營區": "Tainan",
    "柳營區": "Tainan",
    "鹽水區": "Tainan",
    "善化區": "Tainan",
    "新市區": "Tainan",
    "安定區": "Tainan",
    "山上區": "Tainan",
    "大內區": "Tainan",
    # ── 高雄市 ──────────────────────────────────────────────
    "新興區": "Kaohsiung",
    "前金區": "Kaohsiung",
    "苓雅區": "Kaohsiung",
    "鹽埕區": "Kaohsiung",
    "鼓山區": "Kaohsiung",
    "旗津區": "Kaohsiung",
    "前鎮區": "Kaohsiung",
    "三民區": "Kaohsiung",
    "楠梓區": "Kaohsiung",
    "小港區": "Kaohsiung",
    "左營區": "Kaohsiung",
    "仁武區": "Kaohsiung",
    "大社區": "Kaohsiung",
    "岡山區": "Kaohsiung",
    "路竹區": "Kaohsiung",
    "阿蓮區": "Kaohsiung",
    "田寮區": "Kaohsiung",
    "燕巢區": "Kaohsiung",
    "橋頭區": "Kaohsiung",
    "梓官區": "Kaohsiung",
    "彌陀區": "Kaohsiung",
    "永安區": "Kaohsiung",
    "湖內區": "Kaohsiung",
    "茄萣區": "Kaohsiung",
    "旗山區": "Kaohsiung",
    "美濃區": "Kaohsiung",
    "六龜區": "Kaohsiung",
    "內門區": "Kaohsiung",
    "杉林區": "Kaohsiung",
    "甲仙區": "Kaohsiung",
    "桃源區": "Kaohsiung",
    "那瑪夏區": "Kaohsiung",
    "茂林區": "Kaohsiung",
    "鳳山區": "Kaohsiung",
    "林園區": "Kaohsiung",
    "大寮區": "Kaohsiung",
    "鳥松區": "Kaohsiung",
    "大樹區": "Kaohsiung",
    # ── 基隆市（跳過歧義：信義區/中正區/中山區）────────────────
    "仁愛區": "Keelung",
    "安樂區": "Keelung",
    "暖暖區": "Keelung",
    "七堵區": "Keelung",
    # ── 新竹市（跳過歧義：東區/北區）─────────────────────────
    "香山區": "Hsinchu",
    # ── 嘉義市（跳過歧義：東區/西區）全部歧義，無唯一項 ───────────
    # ── 宜蘭縣 ──────────────────────────────────────────────
    "宜蘭市": "YilanCounty",
    "頭城鎮": "YilanCounty",
    "羅東鎮": "YilanCounty",
    "蘇澳鎮": "YilanCounty",
    "礁溪鄉": "YilanCounty",
    "壯圍鄉": "YilanCounty",
    "員山鄉": "YilanCounty",
    "冬山鄉": "YilanCounty",
    "五結鄉": "YilanCounty",
    "三星鄉": "YilanCounty",
    "大同鄉": "YilanCounty",
    "南澳鄉": "YilanCounty",
    # ── 新竹縣 ──────────────────────────────────────────────
    "竹北市": "HsinchuCounty",
    "關西鎮": "HsinchuCounty",
    "新埔鎮": "HsinchuCounty",
    "竹東鎮": "HsinchuCounty",
    "湖口鄉": "HsinchuCounty",
    "橫山鄉": "HsinchuCounty",
    "新豐鄉": "HsinchuCounty",
    "芎林鄉": "HsinchuCounty",
    "寶山鄉": "HsinchuCounty",
    "北埔鄉": "HsinchuCounty",
    "峨眉鄉": "HsinchuCounty",
    "尖石鄉": "HsinchuCounty",
    "五峰鄉": "HsinchuCounty",
    # ── 苗栗縣 ──────────────────────────────────────────────
    "苗栗市": "MiaoliCounty",
    "頭份市": "MiaoliCounty",
    "竹南鎮": "MiaoliCounty",
    "通霄鎮": "MiaoliCounty",
    "後龍鎮": "MiaoliCounty",
    "苑裡鎮": "MiaoliCounty",
    "卓蘭鎮": "MiaoliCounty",
    "南庄鄉": "MiaoliCounty",
    "獅潭鄉": "MiaoliCounty",
    "三灣鄉": "MiaoliCounty",
    "頭屋鄉": "MiaoliCounty",
    "造橋鄉": "MiaoliCounty",
    "公館鄉": "MiaoliCounty",
    "銅鑼鄉": "MiaoliCounty",
    "三義鄉": "MiaoliCounty",
    "西湖鄉": "MiaoliCounty",
    "大湖鄉": "MiaoliCounty",
    "泰安鄉": "MiaoliCounty",
    # ── 彰化縣 ──────────────────────────────────────────────
    "彰化市": "ChanghuaCounty",
    "員林市": "ChanghuaCounty",
    "鹿港鎮": "ChanghuaCounty",
    "和美鎮": "ChanghuaCounty",
    "北斗鎮": "ChanghuaCounty",
    "溪湖鎮": "ChanghuaCounty",
    "田中鎮": "ChanghuaCounty",
    "二林鎮": "ChanghuaCounty",
    "線西鄉": "ChanghuaCounty",
    "伸港鄉": "ChanghuaCounty",
    "福興鄉": "ChanghuaCounty",
    "秀水鄉": "ChanghuaCounty",
    "花壇鄉": "ChanghuaCounty",
    "芬園鄉": "ChanghuaCounty",
    "大村鄉": "ChanghuaCounty",
    "埔鹽鄉": "ChanghuaCounty",
    "埔心鄉": "ChanghuaCounty",
    "永靖鄉": "ChanghuaCounty",
    "社頭鄉": "ChanghuaCounty",
    "二水鄉": "ChanghuaCounty",
    "田尾鄉": "ChanghuaCounty",
    "埤頭鄉": "ChanghuaCounty",
    "芳苑鄉": "ChanghuaCounty",
    "大城鄉": "ChanghuaCounty",
    "竹塘鄉": "ChanghuaCounty",
    "溪州鄉": "ChanghuaCounty",
    # ── 南投縣 ──────────────────────────────────────────────
    "南投市": "NantouCounty",
    "埔里鎮": "NantouCounty",
    "草屯鎮": "NantouCounty",
    "竹山鎮": "NantouCounty",
    "集集鎮": "NantouCounty",
    "名間鄉": "NantouCounty",
    "鹿谷鄉": "NantouCounty",
    "中寮鄉": "NantouCounty",
    "魚池鄉": "NantouCounty",
    "國姓鄉": "NantouCounty",
    "水里鄉": "NantouCounty",
    "信義鄉": "NantouCounty",
    "仁愛鄉": "NantouCounty",
    # ── 雲林縣 ──────────────────────────────────────────────
    "斗六市": "YunlinCounty",
    "斗南鎮": "YunlinCounty",
    "虎尾鎮": "YunlinCounty",
    "西螺鎮": "YunlinCounty",
    "土庫鎮": "YunlinCounty",
    "北港鎮": "YunlinCounty",
    "古坑鄉": "YunlinCounty",
    "大埤鄉": "YunlinCounty",
    "莿桐鄉": "YunlinCounty",
    "林內鄉": "YunlinCounty",
    "二崙鄉": "YunlinCounty",
    "水林鄉": "YunlinCounty",
    "口湖鄉": "YunlinCounty",
    "四湖鄉": "YunlinCounty",
    "元長鄉": "YunlinCounty",
    "褒忠鄉": "YunlinCounty",
    "東勢鄉": "YunlinCounty",
    "臺西鄉": "YunlinCounty",
    "台西鄉": "YunlinCounty",
    "崙背鄉": "YunlinCounty",
    "麥寮鄉": "YunlinCounty",
    # ── 嘉義縣 ──────────────────────────────────────────────
    "太保市": "ChiayiCounty",
    "朴子市": "ChiayiCounty",
    "大林鎮": "ChiayiCounty",
    "布袋鎮": "ChiayiCounty",
    "番路鄉": "ChiayiCounty",
    "梅山鄉": "ChiayiCounty",
    "竹崎鄉": "ChiayiCounty",
    "阿里山鄉": "ChiayiCounty",
    "中埔鄉": "ChiayiCounty",
    "大埔鄉": "ChiayiCounty",
    "水上鄉": "ChiayiCounty",
    "鹿草鄉": "ChiayiCounty",
    "東石鄉": "ChiayiCounty",
    "六腳鄉": "ChiayiCounty",
    "新港鄉": "ChiayiCounty",
    "民雄鄉": "ChiayiCounty",
    "溪口鄉": "ChiayiCounty",
    "義竹鄉": "ChiayiCounty",
    # ── 屏東縣 ──────────────────────────────────────────────
    "屏東市": "PingtungCounty",
    "潮州鎮": "PingtungCounty",
    "東港鎮": "PingtungCounty",
    "恆春鎮": "PingtungCounty",
    "三地門鄉": "PingtungCounty",
    "霧臺鄉": "PingtungCounty",
    "瑪家鄉": "PingtungCounty",
    "九如鄉": "PingtungCounty",
    "里港鄉": "PingtungCounty",
    "高樹鄉": "PingtungCounty",
    "鹽埔鄉": "PingtungCounty",
    "長治鄉": "PingtungCounty",
    "麟洛鄉": "PingtungCounty",
    "竹田鄉": "PingtungCounty",
    "內埔鄉": "PingtungCounty",
    "萬丹鄉": "PingtungCounty",
    "泰武鄉": "PingtungCounty",
    "來義鄉": "PingtungCounty",
    "萬巒鄉": "PingtungCounty",
    "崁頂鄉": "PingtungCounty",
    "新埤鄉": "PingtungCounty",
    "南州鄉": "PingtungCounty",
    "林邊鄉": "PingtungCounty",
    "琉球鄉": "PingtungCounty",
    "佳冬鄉": "PingtungCounty",
    "新園鄉": "PingtungCounty",
    "枋寮鄉": "PingtungCounty",
    "枋山鄉": "PingtungCounty",
    "春日鄉": "PingtungCounty",
    "獅子鄉": "PingtungCounty",
    "車城鄉": "PingtungCounty",
    "牡丹鄉": "PingtungCounty",
    "滿州鄉": "PingtungCounty",
    "南灣": "PingtungCounty",      # 恆春鎮下的知名觀光地名（非行政區）
    # ── 臺東縣 ──────────────────────────────────────────────
    "臺東市": "TaitungCounty",
    "台東市": "TaitungCounty",
    "成功鎮": "TaitungCounty",
    "關山鎮": "TaitungCounty",
    "延平鄉": "TaitungCounty",
    "卑南鄉": "TaitungCounty",
    "鹿野鄉": "TaitungCounty",
    "海端鄉": "TaitungCounty",
    "池上鄉": "TaitungCounty",
    "東河鄉": "TaitungCounty",
    "長濱鄉": "TaitungCounty",
    "太麻里鄉": "TaitungCounty",
    "金峰鄉": "TaitungCounty",
    "大武鄉": "TaitungCounty",
    "達仁鄉": "TaitungCounty",
    "綠島鄉": "TaitungCounty",
    "蘭嶼鄉": "TaitungCounty",
    # ── 花蓮縣 ──────────────────────────────────────────────
    "花蓮市": "HualienCounty",
    "鳳林鎮": "HualienCounty",
    "玉里鎮": "HualienCounty",
    "新城鄉": "HualienCounty",
    "秀林鄉": "HualienCounty",
    "吉安鄉": "HualienCounty",
    "壽豐鄉": "HualienCounty",
    "光復鄉": "HualienCounty",
    "豐濱鄉": "HualienCounty",
    "瑞穗鄉": "HualienCounty",
    "萬榮鄉": "HualienCounty",
    "卓溪鄉": "HualienCounty",
    "富里鄉": "HualienCounty",
    # ── 澎湖縣 ──────────────────────────────────────────────
    "馬公市": "PenghuCounty",
    "西嶼鄉": "PenghuCounty",
    "望安鄉": "PenghuCounty",
    "七美鄉": "PenghuCounty",
    "白沙鄉": "PenghuCounty",
    "湖西鄉": "PenghuCounty",
    # ── 金門縣 ──────────────────────────────────────────────
    "金城鎮": "KinmenCounty",
    "金湖鎮": "KinmenCounty",
    "金沙鎮": "KinmenCounty",
    "金寧鄉": "KinmenCounty",
    "烈嶼鄉": "KinmenCounty",
    "烏坵鄉": "KinmenCounty",
    # ── 連江縣 ──────────────────────────────────────────────
    "南竿鄉": "LienchiangCounty",
    "北竿鄉": "LienchiangCounty",
    "莒光鄉": "LienchiangCounty",
    "東引鄉": "LienchiangCounty",

    # ── 常用短名別名（不含後綴，明確無歧義者）──────────────────
    "板橋": "NewTaipei",
    "淡水": "NewTaipei",
    "新店": "NewTaipei",
    "三重": "NewTaipei",
    "新莊": "NewTaipei",
    "蘆洲": "NewTaipei",
    "土城": "NewTaipei",
    "中和": "NewTaipei",
    "永和": "NewTaipei",
    "三峽": "NewTaipei",
    "樹林": "NewTaipei",
    "鶯歌": "NewTaipei",
    "汐止": "NewTaipei",
    "瑞芳": "NewTaipei",
    "中壢": "Taoyuan",
    "平鎮": "Taoyuan",
    "楊梅": "Taoyuan",
    "大溪": "Taoyuan",
    "龜山": "Taoyuan",
    "蘆竹": "Taoyuan",
    "豐原": "Taichung",
    "大甲": "Taichung",
    "清水": "Taichung",
    "沙鹿": "Taichung",
    "梧棲": "Taichung",
    "霧峰": "Taichung",
    "太平": "Taichung",
    "大里": "Taichung",
    "潭子": "Taichung",
    "大雅": "Taichung",
    "烏日": "Taichung",
    "新營": "Tainan",
    "永康": "Tainan",
    "麻豆": "Tainan",
    "善化": "Tainan",
    "佳里": "Tainan",
    "新化": "Tainan",
    "後壁": "Tainan",
    "白河": "Tainan",
    "學甲": "Tainan",
    "岡山": "Kaohsiung",
    "鳳山": "Kaohsiung",
    "旗山": "Kaohsiung",
    "美濃": "Kaohsiung",
    "路竹": "Kaohsiung",
    "橋頭": "Kaohsiung",
    "燕巢": "Kaohsiung",
    "甲仙": "Kaohsiung",
    "六龜": "Kaohsiung",
    "林園": "Kaohsiung",
    "大寮": "Kaohsiung",
    "竹北": "HsinchuCounty",
    "竹東": "HsinchuCounty",
    "新埔": "HsinchuCounty",
    "關西": "HsinchuCounty",
    "湖口": "HsinchuCounty",
    "竹南": "MiaoliCounty",
    "頭份": "MiaoliCounty",
    "苑裡": "MiaoliCounty",
    "通霄": "MiaoliCounty",
    "後龍": "MiaoliCounty",
    "三義": "MiaoliCounty",
    "大湖": "MiaoliCounty",
    "卓蘭": "MiaoliCounty",
    "鹿港": "ChanghuaCounty",
    "員林": "ChanghuaCounty",
    "北斗": "ChanghuaCounty",
    "和美": "ChanghuaCounty",
    "溪湖": "ChanghuaCounty",
    "二林": "ChanghuaCounty",
    "田中": "ChanghuaCounty",
    "埔里": "NantouCounty",
    "草屯": "NantouCounty",
    "竹山": "NantouCounty",
    "集集": "NantouCounty",
    "斗六": "YunlinCounty",
    "斗南": "YunlinCounty",
    "虎尾": "YunlinCounty",
    "西螺": "YunlinCounty",
    "北港": "YunlinCounty",
    "土庫": "YunlinCounty",
    "麥寮": "YunlinCounty",
    "古坑": "YunlinCounty",
    "朴子": "ChiayiCounty",
    "太保": "ChiayiCounty",
    "大林": "ChiayiCounty",
    "民雄": "ChiayiCounty",
    "新港": "ChiayiCounty",
    "竹崎": "ChiayiCounty",
    "阿里山": "ChiayiCounty",
    "潮州": "PingtungCounty",
    "東港": "PingtungCounty",
    "恆春": "PingtungCounty",
    "里港": "PingtungCounty",
    "內埔": "PingtungCounty",
    "萬丹": "PingtungCounty",
    "林邊": "PingtungCounty",
    "枋寮": "PingtungCounty",
    "枋山": "PingtungCounty",
    "佳冬": "PingtungCounty",
    "新園": "PingtungCounty",
    "高樹": "PingtungCounty",
    "長治": "PingtungCounty",
    "滿州": "PingtungCounty",
    "羅東": "YilanCounty",
    "蘇澳": "YilanCounty",
    "礁溪": "YilanCounty",
    "冬山": "YilanCounty",
    "三星": "YilanCounty",
    "頭城": "YilanCounty",
    "壯圍": "YilanCounty",
    "玉里": "HualienCounty",
    "鳳林": "HualienCounty",
    "吉安": "HualienCounty",
    "壽豐": "HualienCounty",
    "光復": "HualienCounty",
    "瑞穗": "HualienCounty",
    "富里": "HualienCounty",
    "池上": "TaitungCounty",
    "關山": "TaitungCounty",
    "成功": "TaitungCounty",
    "鹿野": "TaitungCounty",
    "長濱": "TaitungCounty",
    "蘭嶼": "TaitungCounty",
    "綠島": "TaitungCounty",
    "馬公": "PenghuCounty",
    "七美": "PenghuCounty",
    "白沙": "PenghuCounty",
    "西嶼": "PenghuCounty",
    "金城": "KinmenCounty",
    "金湖": "KinmenCounty",
    "金沙": "KinmenCounty",
    "金寧": "KinmenCounty",
    "烈嶼": "KinmenCounty",
    "東引": "LienchiangCounty",
    "南竿": "LienchiangCounty",
    "北竿": "LienchiangCounty",
    "莒光": "LienchiangCounty",
}

# 跨縣市同名鄉鎮市區（同一名稱出現在多個縣市）
AMBIGUOUS_DISTRICTS: dict[str, list[str]] = {
    "大安區": ["臺北市", "臺中市"],
    "東區": ["臺中市", "臺南市", "新竹市", "嘉義市"],
    "南區": ["臺中市", "臺南市"],
    "北區": ["臺中市", "臺南市", "新竹市"],
    "西區": ["臺中市", "嘉義市"],
    "中正區": ["臺北市", "基隆市"],
    "信義區": ["臺北市", "基隆市"],
    "中山區": ["臺北市", "基隆市"],
}


def resolve_city(raw: str | None) -> dict[str, object]:
    """Resolve a common Chinese city alias into TDX City."""

    value = (raw or "").strip()
    if not value:
        return {
            "status": "invalid_input",
            "normalized_value": None,
            "needs_clarification": True,
            "candidates": [],
            "details": {"reason": "missing_city"},
        }

    # 1. 直接縣市名稱對照
    match = CITY_ALIASES.get(value)
    if match:
        return {
            "status": "ok",
            "normalized_value": match["city"],
            "needs_clarification": False,
            "candidates": [],
            "details": {"label": match["label"], "raw": value},
        }

    # 2. 鄉鎮市區落點查詢（無歧義）
    city_code = DISTRICT_TO_CITY.get(value)
    if city_code:
        label = _CITY_CODE_TO_LABEL.get(city_code, city_code)
        return {
            "status": "ok",
            "normalized_value": city_code,
            "needs_clarification": False,
            "candidates": [],
            "details": {"label": label, "raw": value, "matched_by": "district"},
        }

    # 3. 跨縣市同名歧義
    if value in AMBIGUOUS_DISTRICTS:
        return {
            "status": "needs_clarification",
            "normalized_value": None,
            "needs_clarification": True,
            "candidates": AMBIGUOUS_DISTRICTS[value],
            "details": {"reason": "ambiguous_district", "raw": value},
        }

    return {
        "status": "needs_clarification",
        "normalized_value": None,
        "needs_clarification": True,
        "candidates": sorted({entry["label"] for entry in CITY_ALIASES.values()}),
        "details": {"reason": "unknown_city_alias", "raw": value},
    }
